name 'deploy_app'
maintainer 'You'
maintainer_email 'you@example.com'
license 'Apache-2.0'
description 'Deploys hello-jenkins app from Jenkins artifacts and manages it as a systemd service'
version '0.1.0'
supports 'amazon'
supports 'redhat'
supports 'ubuntu'
